version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: peff6/my-go-app
    ports:
      - "3000:3000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend/test.db:/app/backend/test.db
    command: ./server
